import { describe, expect, it } from 'vitest';
import { calculateInvoiceLine, calculateInvoiceTotals, formatMinor, parseScaledDecimal, percentageToBasisPoints } from '../domain/invoice';
const line = (change: Record<string, unknown> = {}) => ({ position: 0, designation: 'Audit', quantityScaled: 1, quantityScale: 0, unitPriceMinor: 1000, discountType: 'NONE' as const, discountValue: 0, taxRateBasisPoints: 0, ...change });
describe('Moteur financier Sprint 5 BR-120 à BR-129', () => {
  it('calcule XOF entier, prix zéro et affichage sans décimale', () => { expect(calculateInvoiceLine(line(), false).lineTotalMinor).toBe(1000); expect(calculateInvoiceLine(line({ unitPriceMinor: 0 }), false).lineTotalMinor).toBe(0); expect(formatMinor(1234567, 'XOF', 0)).toBe('1 234 567 XOF'); });
  it('affiche une devise à deux décimales sans flottant source', () => expect(formatMinor(12345, 'EUR', 2)).toBe('123,45 EUR'));
  it('calcule quantités entière et décimale mise à l’échelle', () => { expect(calculateInvoiceLine(line({ quantityScaled: 2 }), false).grossMinor).toBe(2000); expect(calculateInvoiceLine(line({ quantityScaled: 1500, quantityScale: 3 }), false).grossMinor).toBe(1500); expect(parseScaledDecimal('1,500')).toEqual({ scaled: 1500, scale: 3 }); });
  it.each([{ quantityScaled: 0 }, { quantityScaled: -1 }, { unitPriceMinor: -1 }, { quantityScaled: Number.NaN }, { unitPriceMinor: Number.POSITIVE_INFINITY }])('refuse quantité ou prix invalide %#', (change) => expect(() => calculateInvoiceLine(line(change), false)).toThrow());
  it('applique une remise montant', () => expect(calculateInvoiceLine(line({ discountType: 'AMOUNT', discountValue: 250 }), false)).toMatchObject({ grossMinor: 1000, discountMinor: 250, lineTotalMinor: 750 }));
  it('applique une remise pourcentage en points de base', () => expect(calculateInvoiceLine(line({ discountType: 'PERCENT', discountValue: 1250 }), false)).toMatchObject({ discountMinor: 125, lineTotalMinor: 875 }));
  it('autorise une remise égale au brut et refuse une remise supérieure', () => { expect(calculateInvoiceLine(line({ discountType: 'AMOUNT', discountValue: 1000 }), false).lineTotalMinor).toBe(0); expect(() => calculateInvoiceLine(line({ discountType: 'AMOUNT', discountValue: 1001 }), false)).toThrow(/dépasser/); expect(() => calculateInvoiceLine(line({ discountType: 'PERCENT', discountValue: 10001 }), false)).toThrow(); });
  it('force taxe et taux à zéro lorsque les taxes sont désactivées', () => expect(calculateInvoiceLine(line({ taxRateBasisPoints: 1800 }), false)).toMatchObject({ taxRateBasisPoints: 0, taxMinor: 0, lineTotalMinor: 1000 }));
  it('calcule taxe active, taux nul et arrondi demi-unité vers le haut', () => { expect(calculateInvoiceLine(line({ taxRateBasisPoints: 1800 }), true).taxMinor).toBe(180); expect(calculateInvoiceLine(line(), true).taxMinor).toBe(0); expect(calculateInvoiceLine(line({ unitPriceMinor: 1, taxRateBasisPoints: 5000 }), true).taxMinor).toBe(1); });
  it('convertit un taux décimal configuré en points de base sans multiplication flottante', () => { expect(percentageToBasisPoints('18,125')).toBe(1813); expect(percentageToBasisPoints(0)).toBe(0); expect(() => percentageToBasisPoints('100,01')).toThrow(/100/); });
  it('agrège plusieurs lignes de manière cohérente', () => { const lines = [calculateInvoiceLine(line(), false), calculateInvoiceLine(line({ unitPriceMinor: 500, discountType: 'AMOUNT', discountValue: 100, taxRateBasisPoints: 1000 }), true)]; expect(calculateInvoiceTotals(lines)).toEqual({ subtotalMinor: 1400, discountTotalMinor: 100, taxTotalMinor: 40, grandTotalMinor: 1440 }); });
  it('refuse les dépassements de la plage sûre', () => expect(() => calculateInvoiceLine(line({ quantityScaled: 1_000_000_000, unitPriceMinor: Number.MAX_SAFE_INTEGER }), false)).toThrow(/plage/));
});
