/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
'use client';

import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ManageFollowUpsUseCase } from '@/modules/follow-ups/application/manage-follow-ups';
import { FollowUpRecord } from '@/modules/follow-ups/domain/follow-up';
import { DexieProspectRepository } from '@/modules/prospects/infrastructure/dexie-prospect-repository';
import { ManageMessageTemplatesUseCase } from '@/modules/messages/application/manage-message-templates';
import { ResolveProspectMessageUseCase } from '@/modules/messages/application/resolve-prospect-message';

const manage = new ManageFollowUpsUseCase(); const prospects = new DexieProspectRepository(); const templates = new ManageMessageTemplatesUseCase(); const resolver = new ResolveProspectMessageUseCase();
export default function FollowUpDetailPage() {
  const { id } = useParams() as { id: string }; const router = useRouter();
  const [item, setItem] = useState<FollowUpRecord>(); const [contactName, setContactName] = useState(''); const [message, setMessage] = useState(''); const [unresolved, setUnresolved] = useState<string[]>([]); const [whatsAppUrl, setWhatsAppUrl] = useState(''); const [note, setNote] = useState(''); const [nextDate, setNextDate] = useState(''); const [feedback, setFeedback] = useState('');
  const load = async () => { const record = await manage.get(id); setItem(record); if (!record) return; setContactName((await prospects.getById(record.contactId))?.contact.displayName || 'Contact archivé'); if (record.messageSnapshot) setMessage(record.messageSnapshot); else if (record.messageTemplateId) { const template = await templates.get(record.messageTemplateId); if (template) { const resolution = await resolver.execute(record.contactId, template.content); setMessage(resolution.text); setUnresolved(resolution.unresolved); } } };
  useEffect(() => { void load(); }, [id]);
  if (!item) return <p className="p-4">Chargement...</p>;
  const planned = item.status === 'PLANIFIEE';
  const prepare = async (allowEmpty = false) => { let final = message; if (unresolved.length && allowEmpty) { const template = item.messageTemplateId ? await templates.get(item.messageTemplateId) : undefined; if (template) { const resolution = await resolver.execute(item.contactId, template.content, true); final = resolution.text; setMessage(final); setUnresolved([]); } } if (unresolved.length && !allowEmpty) { setFeedback('Complétez le message ou confirmez la substitution vide.'); return; } const result = await manage.prepareWhatsApp(id, final); setWhatsAppUrl(result.url); setItem(result.followUp); setFeedback('Lien WhatsApp préparé. La relance reste planifiée.'); };
  return <main className="mx-auto max-w-2xl space-y-5 p-4 md:p-8"><Link href="/follow-ups" className="text-blue-700">← Relances</Link><section className="rounded-xl border bg-card text-card-foreground p-5"><div className="flex justify-between"><div><h1 className="text-2xl font-bold">{contactName}</h1><p>{new Date(item.dueAt).toLocaleString('fr-FR', { timeZone: item.timezone })}</p></div><span className="font-semibold">{item.status}</span></div><p className="mt-3">{item.priority} · {item.channel} · {item.reason || 'Sans motif'}</p>{item.previousFollowUpId && <p className="text-sm">Report de <Link className="text-blue-700" href={`/follow-ups/${item.previousFollowUpId}`}>{item.previousFollowUpId}</Link></p>}</section>
    {item.channel === 'WHATSAPP' && <section className="space-y-3 rounded-xl border bg-card text-card-foreground p-5"><h2 className="font-semibold">Prévisualisation WhatsApp</h2>{unresolved.length > 0 && <p role="alert" className="text-amber-800">Variables sans valeur : {unresolved.join(', ')}</p>}<textarea aria-label="Message final WhatsApp" value={message} onChange={(e) => { setMessage(e.target.value); setUnresolved([]); }} rows={7} className="w-full rounded-md border p-3"/><p className="text-xs">WhatsApp est externe; l’ouverture ne prouve ni l’envoi ni la livraison.</p><div className="flex flex-wrap gap-2"><button onClick={() => void prepare()} className="rounded-md bg-green-700 px-4 py-3 text-white">Préparer le lien</button>{unresolved.length > 0 && <button onClick={() => void prepare(true)} className="rounded-md border px-4 py-3">Substituer vide et confirmer</button>}{whatsAppUrl && <a data-testid="whatsapp-link" href={whatsAppUrl} target="_blank" rel="noopener noreferrer" className="rounded-md border border-green-700 px-4 py-3 text-green-800">Ouvrir WhatsApp</a>}</div></section>}
    {feedback && <p role="status" className="rounded-md bg-blue-50 p-3">{feedback}</p>}
    {planned && <section className="space-y-4 rounded-xl border bg-card text-card-foreground p-5"><div className="flex gap-2"><Link href={`/follow-ups/${id}/edit`} className="rounded-md border px-4 py-3">Modifier</Link><button onClick={async () => { if (confirm('Annuler cette relance ?')) { await manage.cancel(id); await load(); } }} className="rounded-md border border-red-600 px-4 py-3 text-red-700">Annuler</button></div><label className="block">Note de résultat<textarea aria-label="Note de résultat" value={note} onChange={(e) => setNote(e.target.value)} className="mt-1 w-full rounded-md border p-3"/></label><button onClick={async () => { await manage.complete(id, note); await load(); }} className="h-11 w-full rounded-md bg-blue-600 text-white">Marquer comme réalisée</button><label className="block">Nouvelle échéance<input aria-label="Nouvelle échéance" type="datetime-local" value={nextDate} onChange={(e) => setNextDate(e.target.value)} className="mt-1 h-11 w-full rounded-md border px-3"/></label><button onClick={async () => { const next = await manage.reschedule(id, new Date(nextDate).toISOString(), item.timezone); router.push(`/follow-ups/${next.id}`); }} className="h-11 w-full rounded-md border">Reporter</button></section>}
  </main>;
}
