'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { GetStatisticsUseCase } from '../application/get-statistics';
import { formatMinorExact, formatQuantityExact, PERIOD_PRESETS, PeriodPreset, StatisticsReport } from '../domain/statistics';
import { AccessibleBars } from './AccessibleBars';

const getStatistics = new GetStatisticsUseCase();
const PRESET_LABELS: Record<PeriodPreset, string> = { TODAY: 'Aujourd’hui', LAST_7_DAYS: '7 derniers jours', CURRENT_MONTH: 'Mois en cours', PREVIOUS_MONTH: 'Mois précédent', CURRENT_YEAR: 'Année en cours', CUSTOM: 'Personnalisée' };

function Money({ minor, currency, scale }: { minor: string; currency: string; scale: number }) { return <>{formatMinorExact(minor, currency, scale)}</>; }
function MetricCard({ label, value, detail, tone = 'default' }: { label: string; value: React.ReactNode; detail: string; tone?: 'default' | 'blue' | 'green' | 'amber' }) {
  const tones = { default: 'border-border', blue: 'border-blue-500/20 bg-blue-500/10', green: 'border-emerald-500/20 bg-emerald-500/10', amber: 'border-amber-500/20 bg-amber-500/10' };
  return <article className={`rounded-xl border p-4 ${tones[tone]}`}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></article>;
}
function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return <section className="rounded-xl border bg-card p-4 shadow-sm sm:p-5"><div className="mb-4"><h2 className="text-lg font-semibold">{title}</h2>{subtitle && <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>}</div>{children}</section>;
}
function changeLabel(current: number, previous: number): string { const delta = current - previous; return `${delta > 0 ? '+' : ''}${delta} par rapport à la période précédente`; }
function moneyChange(current: string, previous: string, currency: string, scale: number): string { const delta = BigInt(current) - BigInt(previous); return `${delta > BigInt(0) ? '+' : ''}${formatMinorExact(delta.toString(), currency, scale)} vs période précédente`; }
function amountFor(rows: Array<{ currency: string; currencyScale: number; minor: string }>, currency: string, scale: number): string { return rows.find((item) => item.currency === currency && item.currencyScale === scale)?.minor ?? '0'; }

export function PeriodSelector({ preset, from, to, includeArchivedProducts = false, pending, onApply }: { preset: PeriodPreset; from: string; to: string; includeArchivedProducts?: boolean; pending: boolean; onApply: (value: { preset: PeriodPreset; from?: string; to?: string; includeArchivedProducts: boolean }) => void }) {
  const [selected, setSelected] = useState(preset); const [customFrom, setCustomFrom] = useState(from); const [customTo, setCustomTo] = useState(to); const [showArchived, setShowArchived] = useState(includeArchivedProducts);
  const submit = (event: FormEvent) => { event.preventDefault(); onApply({ preset: selected, from: selected === 'CUSTOM' ? customFrom : undefined, to: selected === 'CUSTOM' ? customTo : undefined, includeArchivedProducts: showArchived }); };
  return <form onSubmit={submit} className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-[minmax(12rem,1fr)_auto_auto_auto] sm:items-end">
    <label className="grid gap-1 text-sm"><span>Période d’analyse</span><select aria-label="Période d’analyse" className="h-10 rounded-md border bg-background px-3" value={selected} onChange={(event) => setSelected(event.target.value as PeriodPreset)}>{PERIOD_PRESETS.map((value) => <option key={value} value={value}>{PRESET_LABELS[value]}</option>)}</select></label>
    {selected === 'CUSTOM' && <><label className="grid gap-1 text-sm"><span>Du</span><input aria-label="Début de période" className="h-10 rounded-md border px-3" type="date" value={customFrom} onChange={(event) => setCustomFrom(event.target.value)} required /></label><label className="grid gap-1 text-sm"><span>Au</span><input aria-label="Fin de période" className="h-10 rounded-md border px-3" type="date" value={customTo} onChange={(event) => setCustomTo(event.target.value)} required /></label></>}
    <label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={showArchived} onChange={(event) => setShowArchived(event.target.checked)} /> Inclure les produits archivés</label><button className="h-10 rounded-md bg-slate-900 px-4 text-sm font-medium text-white disabled:opacity-60" disabled={pending}>{pending ? 'Calcul…' : 'Appliquer'}</button>
  </form>;
}

export function StatisticsView({ report, detailed = false, onRefresh, pending = false }: { report: StatisticsReport; detailed?: boolean; onRefresh?: () => void; pending?: boolean }) {
  const money = report.primaryFinancial; const primary = { currency: report.primaryCurrency, scale: report.primaryCurrencyScale };
  const demandedTotal = report.demandedProducts.reduce((sum, item) => sum + item.count, 0);
  if (report.isEmpty) return <div className="rounded-2xl border border-dashed p-8 text-center"><h2 className="text-xl font-semibold">Votre activité commerciale commence ici</h2><p className="mx-auto mt-2 max-w-xl text-muted-foreground">Ajoutez un premier prospect pour alimenter le tableau de bord. Les données et calculs restent sur cet appareil.</p><Link className="mt-5 inline-flex h-11 items-center rounded-md bg-blue-600 px-5 font-medium text-white" href="/prospects/nouveau">Ajouter mon premier prospect</Link></div>;
  return <div className="space-y-5">
    {report.integrity.hasIssues && <div role="alert" className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-4 text-sm"><strong>Vérification des données recommandée.</strong> {report.integrity.count} incohérence(s) locale(s) peuvent affecter certains indicateurs. Aucun montant n’a été corrigé silencieusement.</div>}
    {report.hasOtherCurrencies && <div role="status" className="rounded-xl border border-blue-500/20 bg-blue-500/10 p-4 text-sm">Plusieurs devises ou échelles sont présentes. Les cartes principales affichent seulement {report.primaryCurrency}; les montants ne sont jamais additionnés entre devises.</div>}
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Période inclusive : <strong className="text-foreground">{report.period.from} → {report.period.to}</strong> · {report.period.timezone}</p>{onRefresh && <button type="button" onClick={onRefresh} disabled={pending} className="rounded-md border px-3 py-2 text-sm">Actualiser les données</button>}</div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <MetricCard label="Prospects totaux" value={report.prospects.total} detail={`${report.prospects.active} actifs · historique complet`} />
      <MetricCard label="Nouveaux prospects" value={report.prospects.newInPeriod} detail={`${changeLabel(report.prospects.newInPeriod, report.comparison.newProspects)} · date de création`} tone="blue" />
      <MetricCard label="Clients" value={report.clients.total} detail="Contacts convertis uniques, non archivés" />
      <MetricCard label="Taux de conversion" value={report.conversions.ratePercent === null ? 'Non calculable' : `${report.conversions.ratePercent} %`} detail={`${report.conversions.convertedCohort}/${report.conversions.eligibleCohort} prospect(s) de la cohorte de création`} tone="green" />
      <MetricCard label="Relances aujourd’hui" value={report.followUps.today} detail="Échéance à la date locale d’aujourd’hui" tone="blue" />
      <MetricCard label="Relances en retard" value={report.followUps.overdue} detail="Planifiées avant aujourd’hui, sans chevauchement" tone={report.followUps.overdue ? 'amber' : 'default'} />
      <MetricCard label="Montant facturé" value={<Money minor={money.billedMinor} {...primary} />} detail={`Date d’émission · ${moneyChange(money.billedMinor, report.comparison.billedMinor, primary.currency, primary.scale)}`} tone="blue" />
      <MetricCard label="Montant encaissé" value={<Money minor={money.collectedMinor} {...primary} />} detail={`Date de paiement · ${moneyChange(money.collectedMinor, report.comparison.collectedMinor, primary.currency, primary.scale)}`} tone="green" />
      <MetricCard label="Créances actuelles" value={<Money minor={money.receivableMinor} {...primary} />} detail={`${report.receivables.invoices} facture(s) · ${report.receivables.debtorClients} client(s) débiteur(s)`} tone="amber" />
    </div>
    <div className="grid gap-5 lg:grid-cols-2">
      <Section title="Produits les plus demandés" subtitle={`Associations prospect-produit distinctes, par date de demande · produits archivés ${report.includeArchivedProducts ? 'inclus' : 'exclus'}`}>
        <AccessibleBars title="Classement des produits demandés" items={report.demandedProducts.slice(0, 8).map((item) => ({ label: `${item.label}${item.archived ? ' (archivé)' : ''}`, value: item.count, display: `${item.count} demande(s) · ${demandedTotal ? Math.round(item.count * 10000 / demandedTotal) / 100 : 0} %` }))} />
      </Section>
      <Section title="Activité à traiter" subtitle="Comptages locaux en état courant">
        <AccessibleBars title="Relances et campagnes restantes" items={[{ label: 'Relances aujourd’hui', value: report.followUps.today }, { label: 'Relances en retard', value: report.followUps.overdue }, { label: 'Relances à venir', value: report.followUps.upcoming }, { label: 'Destinataires campagne restants', value: report.campaigns.remaining }]} />
      </Section>
    </div>
    <Section title="Actions rapides">
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Link className="rounded-lg border p-3 font-medium hover:bg-muted" href="/prospects/nouveau">Ajouter un prospect</Link><Link className="rounded-lg border p-3 font-medium hover:bg-muted" href="/follow-ups?view=TODAY">Voir les relances du jour</Link><Link className="rounded-lg border p-3 font-medium hover:bg-muted" href="/follow-ups?view=OVERDUE">Voir les relances en retard</Link><Link className="rounded-lg border p-3 font-medium hover:bg-muted" href="/invoices/new">Créer une facture</Link><Link className="rounded-lg border p-3 font-medium hover:bg-muted" href="/invoices">Enregistrer un paiement depuis une facture</Link><Link className="rounded-lg border p-3 font-medium hover:bg-muted" href="/payments?view=RECEIVABLES">Voir les créances</Link><Link className="rounded-lg border p-3 font-medium hover:bg-muted" href="/campaigns/new">Créer une campagne</Link>{report.campaigns.resumableCampaignId ? <Link className="rounded-lg border p-3 font-medium hover:bg-muted" href={`/campaigns/${report.campaigns.resumableCampaignId}/run`}>Reprendre une campagne</Link> : <Link className="rounded-lg border p-3 font-medium hover:bg-muted" href="/campaigns">Reprendre une campagne</Link>}</div>
    </Section>
    <Section title="Alertes utiles" subtitle="État courant, sans notification push"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Relances en retard" value={report.followUps.overdue} detail="Actions planifiées avant aujourd’hui" tone={report.followUps.overdue ? 'amber' : 'default'} /><MetricCard label="Factures échues" value={report.receivables.overdueInvoices} detail="Solde positif et échéance passée" tone={report.receivables.overdueInvoices ? 'amber' : 'default'} /><MetricCard label="Campagnes en cours" value={report.campaigns.inProgress} detail="Traitement manuel à poursuivre" /><MetricCard label="Factures partielles" value={report.receivables.partiallyPaidInvoices} detail="Paiement commencé, solde positif" /></div></Section>
    {!detailed && <p className="text-center"><Link href="/statistics" className="font-medium text-blue-800 dark:text-blue-200 underline">Voir toutes les statistiques</Link></p>}
    {detailed && <>
      <div className="grid gap-5 lg:grid-cols-2">
        <Section title="Conversions" subtitle="Conversions datées dans la période; cohorte formée par la date de création"><div className="grid gap-3 sm:grid-cols-2"><MetricCard label="Conversions dans la période" value={report.conversions.inPeriod} detail={`${changeLabel(report.conversions.inPeriod, report.comparison.conversions)} · date de conversion`} /><MetricCard label="Délai moyen" value={report.conversions.averageDelayDays === null ? 'Non calculable' : `${report.conversions.averageDelayDays} jours`} detail={`${report.conversions.invalidDelayCount} date(s) incohérente(s) exclue(s)`} /></div><p className="mt-3 text-xs text-muted-foreground">Une conversion postérieure à la période compte dans le taux de sa cohorte de création : le taux historique peut donc progresser.</p></Section>
        <Section title="Relances" subtitle="Aujourd’hui et retard sont mutuellement exclusifs"><AccessibleBars title="Répartition des relances" items={[{ label: 'Aujourd’hui', value: report.followUps.today }, { label: 'En retard', value: report.followUps.overdue }, { label: 'À venir', value: report.followUps.upcoming }, { label: 'Réalisées dans la période', value: report.followUps.completedInPeriod }]} /></Section>
      </div>
      <Section title="Flux financiers" subtitle="Facturé = émission dans la période · encaissé = paiement actif dans la période · créances = état courant">
        <div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Facturé" value={<Money minor={money.billedMinor} {...primary} />} detail="Factures émises non annulées" tone="blue" /><MetricCard label="Encaissé" value={<Money minor={money.collectedMinor} {...primary} />} detail="Paiements actifs, contrepassations exclues" tone="green" /><MetricCard label="Restant dû" value={<Money minor={money.receivableMinor} {...primary} />} detail={`${formatMinorExact(money.overdueMinor, primary.currency, primary.scale)} en retard · ${formatMinorExact(money.upcomingMinor, primary.currency, primary.scale)} à venir`} tone="amber" /></div>
        {report.financial.length > 1 && <ul className="mt-4 grid gap-2 sm:grid-cols-2">{report.financial.map((row) => <li key={`${row.currency}-${row.currencyScale}`} className="rounded-lg bg-muted p-3 text-sm"><strong>{row.currency} · échelle {row.currencyScale}</strong><br />Facturé {formatMinorExact(row.billedMinor, row.currency, row.currencyScale)} · encaissé {formatMinorExact(row.collectedMinor, row.currency, row.currencyScale)} · restant {formatMinorExact(row.receivableMinor, row.currency, row.currencyScale)}</li>)}</ul>}
      </Section>
      <div className="grid gap-5 lg:grid-cols-2">
        <Section title="Produits vendus" subtitle={`Quantités exactes des lignes non gratuites, factures émises non annulées · produits archivés ${report.includeArchivedProducts ? 'inclus' : 'exclus'}`}><AccessibleBars title="Classement des produits vendus" items={report.soldProducts.slice(0, 10).map((item) => ({ label: `${item.label}${item.archived ? ' (archivé)' : ''}`, value: item.quantityScaled, display: `${formatQuantityExact(item.quantityScaled, item.quantityScale)} · ${formatMinorExact(amountFor(item.amounts, primary.currency, primary.scale), primary.currency, primary.scale)} · ${item.invoiceCount} facture(s) · ${item.clientCount} client(s)${item.freeLineCount ? ` · ${item.freeLineCount} gratuite(s) exclue(s)` : ''}` }))} /><p className="mt-3 text-xs text-muted-foreground">Les lignes libres sont regroupées par désignation d’instantané. {report.freeInvoiceLineCount} ligne(s) gratuite(s) séparée(s).</p></Section>
        <Section title="Échéancier des créances" subtitle="Nombre de factures en retard par ancienneté"><AccessibleBars title="Ancienneté des créances" items={[{ label: '0–30 jours', value: report.receivables.aging.days0to30 }, { label: '31–60 jours', value: report.receivables.aging.days31to60 }, { label: '61–90 jours', value: report.receivables.aging.days61to90 }, { label: 'Plus de 90 jours', value: report.receivables.aging.daysOver90 }]} /><h3 className="mt-5 font-semibold">Principaux clients débiteurs</h3>{report.receivables.topDebtors.length ? <ul className="mt-2 space-y-2">{report.receivables.topDebtors.map((item) => <li key={item.clientProfileId} className="flex justify-between gap-4 rounded-lg bg-muted p-3"><span>{item.label}</span><strong>{formatMinorExact(amountFor(item.amounts, primary.currency, primary.scale), primary.currency, primary.scale)}</strong></li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">Aucun client débiteur.</p>}</Section>
      </div>

      <div className="grid gap-5 lg:grid-cols-2">
        <Section title="Prospects par localité" subtitle="Localité actuelle du contact; les changements ne sont pas historisés"><AccessibleBars title="Répartition des prospects par localité" items={report.localities.slice(0, 12).map((item) => ({ label: `${item.label}${item.archived ? ' (archivée)' : ''}`, value: item.prospects, display: `${item.prospects} prospect(s) · ${item.clients} client(s) · ${item.conversions} conversion(s) · ${formatMinorExact(amountFor(item.billed, primary.currency, primary.scale), primary.currency, primary.scale)} facturé · ${formatMinorExact(amountFor(item.collected, primary.currency, primary.scale), primary.currency, primary.scale)} encaissé · ${formatMinorExact(amountFor(item.receivable, primary.currency, primary.scale), primary.currency, primary.scale)} dû · ${item.invoiceCount} facture(s)` }))} /></Section>
        <Section title="Prospects par source" subtitle="Taux basé sur la cohorte créée dans la période"><AccessibleBars title="Répartition des prospects par source" items={report.sources.map((item) => ({ label: item.label, value: item.prospects, display: `${item.prospects} prospect(s) · ${item.clients} client(s) · taux ${item.eligibleCohort ? `${Math.round(item.convertedCohort * 10000 / item.eligibleCohort) / 100} % (${item.convertedCohort}/${item.eligibleCohort})` : 'Non calculable (0/0)'}` }))} /></Section>
        <Section title="Statuts actuels" subtitle="Profils prospects actifs, état courant"><AccessibleBars title="Répartition des statuts prospects" items={report.statuses.map((item) => ({ label: item.label, value: item.count }))} /></Section>
        <Section title="Niveaux d’intérêt actuels" subtitle="Profils prospects actifs, état courant"><AccessibleBars title="Répartition des niveaux d’intérêt" items={report.interestLevels.map((item) => ({ label: item.label, value: item.count }))} /></Section>
      </div>
      <Section title="Campagnes assistées" subtitle="Aucune mesure de livraison, lecture, réponse ou ROI n’est déduite"><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><MetricCard label="Total" value={report.campaigns.total} detail="Campagnes actives" /><MetricCard label="Brouillons" value={report.campaigns.draft} detail="Non lancées" /><MetricCard label="Prêtes" value={report.campaigns.ready} detail="Audience prête" /><MetricCard label="En cours" value={report.campaigns.inProgress} detail="Traitement manuel" /><MetricCard label="Restants" value={report.campaigns.remaining} detail="À traiter ou ouverts" /><MetricCard label="Confirmés" value={report.campaigns.confirmed} detail="Confirmation manuelle" /></div></Section>
    </>}
  </div>;
}

export function StatisticsDashboard({ detailed = false }: { detailed?: boolean }) {
  const [report, setReport] = useState<StatisticsReport | null>(null); const [error, setError] = useState(''); const [pending, setPending] = useState(true);
  const [selection, setSelection] = useState<{ preset: PeriodPreset; from?: string; to?: string; includeArchivedProducts?: boolean }>({ preset: 'CURRENT_MONTH', includeArchivedProducts: false });
  const load = useCallback(async (next = selection) => { setPending(true); setError(''); try { setReport(await getStatistics.execute(next)); setSelection(next); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Calcul des statistiques impossible'); } finally { setPending(false); } }, [selection]);
  useEffect(() => { void getStatistics.execute({ preset: 'CURRENT_MONTH' }).then(setReport).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Calcul des statistiques impossible')).finally(() => setPending(false)); }, []);
  if (!report && pending) return <div role="status" className="p-8 text-center">Calcul des statistiques locales…</div>;
  if (!report) return <div role="alert" className="m-4 rounded-xl border border-red-500/20 bg-red-500/10 p-4">{error || 'Données indisponibles.'}</div>;
  return <div className="mx-auto w-full max-w-7xl space-y-5 px-4 py-6 sm:px-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold sm:text-3xl">{detailed ? 'Statistiques commerciales' : 'Tableau de bord'}</h1><p className="mt-1 text-muted-foreground">Indicateurs recalculés localement depuis les données sources.</p></div>{detailed && <Link href="/" className="text-sm font-medium text-blue-800 dark:text-blue-200 underline">Retour au tableau de bord</Link>}</header>{error && <p role="alert" className="rounded-lg border border-red-500/20 bg-red-500/10 p-3 text-sm">{error}</p>}<PeriodSelector preset={selection.preset} from={report.period.from} to={report.period.to} includeArchivedProducts={Boolean(selection.includeArchivedProducts)} pending={pending} onApply={(value) => void load(value)} /><StatisticsView report={report} detailed={detailed} onRefresh={() => void load()} pending={pending} /></div>;
}
