import { db } from '@/infrastructure/database/db';
import { CompanyProfile, InvoiceSettings, SequenceRecord } from '@/modules/settings/domain/settings';
import { TimelineEventRecord } from '@/modules/follow-ups/domain/follow-up';
import { DexieClientRepository } from '@/modules/clients/infrastructure/dexie-client-repository';
import { calculateInvoiceLine, calculateInvoiceTotals, DraftLineInput, InvoiceAggregate, InvoiceFormOptions, InvoiceLineRecord, InvoiceRecord } from '../domain/invoice';
import { sumActivePayments } from '@/modules/payments/domain/payment';

export interface InvoiceSearchCriteria { query?: string; status?: InvoiceRecord['status']; from?: string; to?: string; due?: 'OVERDUE' | 'UPCOMING'; clientProfileId?: string; }
function sameFinancialLine(stored: InvoiceLineRecord, calculated: ReturnType<typeof calculateInvoiceLine>) { return stored.grossMinor === calculated.grossMinor && stored.discountMinor === calculated.discountMinor && stored.taxMinor === calculated.taxMinor && stored.lineTotalMinor === calculated.lineTotalMinor; }

export class DexieInvoiceRepository {
  async hydrate(invoice: InvoiceRecord): Promise<InvoiceAggregate> { const [lines, timelineEvents] = await Promise.all([db.invoiceLines.where('invoiceId').equals(invoice.id).sortBy('position'), db.timelineEvents.where('[sourceEntityType+sourceEntityId]').equals(['INVOICE', invoice.id]).toArray()]); const client = await db.clientProfiles.get(invoice.clientProfileId); const contact = client ? await db.contacts.get(client.contactId) : undefined; const currentClientName = contact?.displayName ?? ''; const clientName = invoice.status === 'BROUILLON' ? currentClientName || invoice.clientSnapshot.displayName : invoice.clientSnapshot.displayName || currentClientName; return { invoice, lines: lines.filter((line) => !line.archivedAt), clientName, timelineEvents: timelineEvents.sort((a, b) => b.occurredAt.localeCompare(a.occurredAt) || b.id.localeCompare(a.id)) }; }
  async get(id: string) { const invoice = await db.invoices.get(id); return invoice ? this.hydrate(invoice) : null; }
  async getRecent(limit: number = 3): Promise<InvoiceRecord[]> { const invoices = await db.invoices.filter(i => !i.archivedAt).toArray(); return invoices.sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, limit); }
  async list(criteria: InvoiceSearchCriteria = {}): Promise<InvoiceAggregate[]> { const invoices = await db.invoices.filter((invoice) => !invoice.archivedAt).toArray(); const values = await Promise.all(invoices.map((invoice) => this.hydrate(invoice))); const query = criteria.query?.trim().toLocaleLowerCase('fr'); const today = new Date().toISOString().slice(0, 10); return values.filter((value) => { const receivable = value.invoice.status === 'EMISE' || value.invoice.status === 'PARTIELLEMENT_PAYEE'; return (!query || value.invoice.number?.toLocaleLowerCase('fr').includes(query) || value.clientName.toLocaleLowerCase('fr').includes(query)) && (!criteria.status || value.invoice.status === criteria.status) && (!criteria.from || (value.invoice.issueDate ?? value.invoice.createdAt.slice(0, 10)) >= criteria.from) && (!criteria.to || (value.invoice.issueDate ?? value.invoice.createdAt.slice(0, 10)) <= criteria.to) && (!criteria.clientProfileId || value.invoice.clientProfileId === criteria.clientProfileId) && (!criteria.due || (criteria.due === 'OVERDUE' ? Boolean(value.invoice.dueDate && value.invoice.dueDate < today && receivable) : Boolean(value.invoice.dueDate && value.invoice.dueDate >= today && receivable))); }).sort((a, b) => (b.invoice.issueDate ?? b.invoice.createdAt).localeCompare(a.invoice.issueDate ?? a.invoice.createdAt) || b.invoice.createdAt.localeCompare(a.invoice.createdAt) || b.invoice.id.localeCompare(a.invoice.id)); }
  async formOptions(): Promise<InvoiceFormOptions> { const [clients, products, companyRecord, settingsRecord] = await Promise.all([new DexieClientRepository().search(), db.products.filter((product) => product.isActive && !product.archivedAt).toArray(), db.settings.get('company.profile'), db.settings.get('invoice.defaults')]); return { clients, products, company: (companyRecord?.value as CompanyProfile | undefined) ?? null, settings: (settingsRecord?.value as InvoiceSettings | undefined) ?? null }; }

  async saveDraft(invoice: InvoiceRecord, lines: InvoiceLineRecord[]): Promise<void> { await db.transaction('rw', db.invoices, db.invoiceLines, async () => { const current = await db.invoices.get(invoice.id); if (current && current.status !== 'BROUILLON') throw new Error('Une facture émise ou annulée est immuable'); const positions = new Set(lines.map((line) => line.position)); if (positions.size !== lines.length) throw new Error('Les positions de lignes doivent être uniques'); await db.invoices.put(invoice); const existing = await db.invoiceLines.where('invoiceId').equals(invoice.id).toArray(); await db.invoiceLines.bulkPut(lines); const removed = existing.filter((line) => !lines.some((next) => next.id === line.id)); if (removed.length) await db.invoiceLines.bulkDelete(removed.map((line) => line.id)); }); }

  async issue(invoiceId: string, now: string): Promise<InvoiceAggregate> {
    await db.transaction('rw', [db.invoices, db.invoiceLines, db.sequences, db.timelineEvents, db.clientProfiles, db.contacts, db.settings], async () => {
      const invoice = await db.invoices.get(invoiceId); if (!invoice) throw new Error('Facture introuvable'); if (invoice.status !== 'BROUILLON') throw new Error('Seul un brouillon peut être émis');
      const lines = (await db.invoiceLines.where('invoiceId').equals(invoiceId).sortBy('position')).filter((line) => !line.archivedAt); if (!lines.length) throw new Error('Une facture émise doit contenir au moins une ligne');
      const profile = await db.clientProfiles.get(invoice.clientProfileId); if (!profile || profile.archivedAt) throw new Error('Client introuvable ou archivé'); const contact = await db.contacts.get(profile.contactId); if (!contact || contact.archivedAt) throw new Error('Client introuvable ou archivé');
      const company = (await db.settings.get('company.profile'))?.value as CompanyProfile | undefined; const settings = (await db.settings.get('invoice.defaults'))?.value as InvoiceSettings | undefined;
      if (!company?.name?.trim() || !company.phone?.trim()) throw new Error('Le profil entreprise est incomplet'); if (!settings) throw new Error('Les paramètres de facturation sont incomplets'); if (settings.currencyCode !== invoice.currency) throw new Error('La devise du brouillon ne correspond plus aux paramètres');
      if (!invoice.issueDate) throw new Error('La date d’émission est obligatoire'); if (invoice.dueDate && invoice.dueDate < invoice.issueDate) throw new Error('L’échéance ne peut pas précéder l’émission');
      const recalculated = lines.map((line) => calculateInvoiceLine({ id: line.id, productId: line.productId, position: line.position, designation: line.designationSnapshot, description: line.descriptionSnapshot, unitLabel: line.unitLabelSnapshot, quantityScaled: line.quantityScaled, quantityScale: line.quantityScale, unitPriceMinor: line.unitPriceMinor, discountType: line.discountType, discountValue: line.discountValue, taxRateBasisPoints: line.taxRateBasisPoints } satisfies DraftLineInput, settings.enableTaxes));
      if (lines.some((line, index) => !sameFinancialLine(line, recalculated[index]))) throw new Error('Les montants de ligne enregistrés sont incohérents'); const totals = calculateInvoiceTotals(recalculated); if (invoice.subtotalMinor !== totals.subtotalMinor || invoice.discountTotalMinor !== totals.discountTotalMinor || invoice.taxTotalMinor !== totals.taxTotalMinor || invoice.grandTotalMinor !== totals.grandTotalMinor) throw new Error('Les totaux enregistrés sont incohérents');
      const year = invoice.issueDate.slice(0, 4); const sequenceKey = `invoice:${year}`; const sequence = await db.sequences.get(sequenceKey); const nextValue = sequence?.nextValue ?? settings.nextValue; if (!Number.isSafeInteger(nextValue) || nextValue < 1) throw new Error('Séquence de facture invalide'); const prefix = settings.prefix.trim(); const padding = sequence?.padding ?? 4; const number = `${prefix}${year}-${String(nextValue).padStart(padding, '0')}`;
      const sequenceRecord: SequenceRecord = { key: sequenceKey, prefix, period: year, nextValue: nextValue + 1, padding, updatedAt: now };
      const issued: InvoiceRecord = { ...invoice, number, status: 'EMISE', companySnapshot: { displayName: company.name, address: [company.address, company.city, company.country].filter(Boolean).join(', ') || undefined, phone: company.phone, email: company.email || undefined, logoDataUri: company.logoDataUri, managerName: company.managerName, managerSignatureDataUri: company.managerSignatureDataUri }, clientSnapshot: { displayName: contact.displayName, address: contact.address, phone: contact.whatsappPhone, email: contact.email || undefined }, ...totals, paidTotalMinor: 0, balanceMinor: totals.grandTotalMinor, issuedAt: now, updatedAt: now };
      const event: TimelineEventRecord = { id: crypto.randomUUID(), contactId: contact.id, type: 'INVOICE_ISSUED', occurredAt: now, createdAt: now, sourceEntityType: 'INVOICE', sourceEntityId: invoice.id, title: `Facture ${number} émise`, summary: `Émission enregistrée en ${invoice.currency}`, payloadVersion: 1 };
      await db.sequences.put(sequenceRecord); await db.invoices.put(issued); await db.timelineEvents.add(event);
    });
    const result = await this.get(invoiceId); if (!result) throw new Error('Facture introuvable après émission'); return result;
  }

  async cancel(invoiceId: string, reason: string, now: string): Promise<InvoiceAggregate> { const trimmed = reason.trim(); if (!trimmed) throw new Error('Le motif d’annulation est obligatoire'); await db.transaction('rw', [db.invoices, db.payments, db.timelineEvents, db.clientProfiles], async () => { const invoice = await db.invoices.get(invoiceId); if (!invoice) throw new Error('Facture introuvable'); if (invoice.status !== 'EMISE') throw new Error('Seule une facture émise sans paiement actif peut être annulée'); const activePayments = await db.payments.where('[invoiceId+status]').equals([invoiceId, 'ACTIVE']).toArray(); if (sumActivePayments(activePayments) !== 0) throw new Error('Contrepassez d’abord tous les paiements actifs'); const profile = await db.clientProfiles.get(invoice.clientProfileId); if (!profile) throw new Error('Client introuvable'); const cancelled = { ...invoice, status: 'ANNULEE' as const, cancelledAt: now, cancellationReason: trimmed, updatedAt: now, paidTotalMinor: 0, balanceMinor: 0 }; const event: TimelineEventRecord = { id: crypto.randomUUID(), contactId: profile.contactId, type: 'INVOICE_CANCELLED', occurredAt: now, createdAt: now, sourceEntityType: 'INVOICE', sourceEntityId: invoice.id, title: `Facture ${invoice.number} annulée`, summary: 'Annulation enregistrée', payloadVersion: 1 }; await db.invoices.put(cancelled); await db.timelineEvents.add(event); }); const result = await this.get(invoiceId); if (!result) throw new Error('Facture introuvable après annulation'); return result; }
}
