'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ManageCampaignsUseCase } from '@/modules/campaigns/application/manage-campaigns';
import { CampaignPreview, segmentationSummary } from '@/modules/campaigns/domain/campaign';
import type { CampaignAggregate } from '@/modules/campaigns/infrastructure/dexie-campaign-repository';

const manage = new ManageCampaignsUseCase();
export default function CampaignDetailPage() {
  const { id } = useParams<{ id: string }>(); const [value, setValue] = useState<CampaignAggregate | null>(); const [preview, setPreview] = useState<CampaignPreview | null>(null); const [error, setError] = useState('');
  const refresh = () => manage.get(id).then((current) => { setValue(current); if (current && (current.campaign.status === 'BROUILLON' || current.campaign.status === 'PRETE')) void manage.preview(current.campaign).then(setPreview); else setPreview(null); });
  useEffect(() => { void manage.get(id).then((current) => { setValue(current); if (current && (current.campaign.status === 'BROUILLON' || current.campaign.status === 'PRETE')) void manage.preview(current.campaign).then(setPreview); }).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Chargement impossible')); }, [id]);
  const action = async (operation: () => Promise<unknown>) => { setError(''); try { await operation(); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Action impossible'); } };
  if (value === undefined) return <p className="p-4">Chargement…</p>; if (value === null) return <p className="p-4">Campagne introuvable.</p>; const { campaign, recipients, progress, template } = value; const mutable = campaign.status === 'BROUILLON' || campaign.status === 'PRETE';
  return <main className="mx-auto max-w-5xl space-y-5 p-4 md:p-8"><Link href="/campaigns" className="text-blue-700">← Campagnes</Link><header className="rounded-xl border bg-card text-card-foreground p-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">{campaign.name}</h1><p>{campaign.objective || 'Sans objectif complémentaire'}</p></div><span className="font-semibold">{campaign.status}</span></div><p className="mt-3 text-sm">Audience : {campaign.audienceType}</p><p className="text-sm">{segmentationSummary(campaign.criteria)}</p></header>{error && <p role="alert" className="rounded-md bg-red-50 p-3 text-red-800">{error}</p>}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><article className="rounded-xl border bg-card text-card-foreground p-3"><small>Destinataires</small><strong className="block">{progress.total || preview?.eligibleCount || 0}</strong></article><article className="rounded-xl border bg-card text-card-foreground p-3"><small>Confirmés</small><strong className="block">{progress.confirmed}</strong></article><article className="rounded-xl border bg-card text-card-foreground p-3"><small>Restants</small><strong className="block">{progress.pending + progress.opened}</strong></article><article className="rounded-xl border bg-card text-card-foreground p-3"><small>Traitement</small><strong className="block">{progress.processedPercent}%</strong></article></section>
    <section className="flex flex-wrap gap-2">{mutable && <Link href={`/campaigns/${id}/edit`} className="rounded border px-4 py-3">Modifier</Link>}{campaign.status === 'BROUILLON' && <button className="rounded bg-emerald-700 px-4 py-3 text-white" onClick={() => void action(() => manage.markReady(id))}>Marquer prête</button>}{campaign.status === 'PRETE' && <><button className="rounded border px-4 py-3" onClick={() => void action(() => manage.backToDraft(id))}>Revenir au brouillon</button><button className="rounded bg-blue-700 px-4 py-3 text-white" onClick={() => { if (window.confirm('Figer cette audience et lancer la campagne ?')) void action(() => manage.launch(id)); }}>Lancer la campagne</button></>}{campaign.status === 'EN_COURS' && <Link href={`/campaigns/${id}/run`} className="rounded bg-blue-700 px-4 py-3 text-white">Traiter les destinataires</Link>}{!['TERMINEE', 'ANNULEE'].includes(campaign.status) && <button className="rounded border border-red-600 px-4 py-3 text-red-700" onClick={() => { const strong = campaign.status !== 'EN_COURS' || window.confirm('Annuler définitivement cette campagne en cours tout en conservant les destinataires traités ?'); if (strong) void action(() => manage.cancel(id, campaign.status === 'EN_COURS')); }}>Annuler la campagne</button>}</section>
    {preview && <section className="rounded-xl border bg-card text-card-foreground p-4"><h2 className="font-semibold">Audience prévisionnelle</h2><p>{preview.rawCount} brut · {preview.eligibleCount} admissible(s) · {preview.invalidPhoneCount} invalide(s) · {preview.duplicateCount} doublon(s) · {preview.manualExclusionCount} exclusion(s) manuelle(s)</p>{preview.entries.filter((item) => !item.eligible).length > 0 && <ul className="mt-3 space-y-1 text-sm">{preview.entries.filter((item) => !item.eligible).map((item) => <li key={item.contactId}>{item.displayName} : {item.exclusionReasons.join(', ')}</li>)}</ul>}</section>}
    <section className="rounded-xl border bg-card text-card-foreground p-4"><h2 className="font-semibold">Message source figé</h2>{template && <p className="text-sm text-muted-foreground">Modèle source : {template.name}{template.archived ? ' (archivé)' : ''}</p>}<p className="mt-2 whitespace-pre-wrap">{campaign.messageSnapshot || 'Message non défini'}</p></section>
    {recipients.length > 0 && <section className="rounded-xl border bg-card text-card-foreground p-4"><h2 className="font-semibold">Destinataires figés</h2><ul className="mt-3 space-y-2">{recipients.map((recipient) => <li key={recipient.id} className="rounded border p-3"><div className="flex justify-between"><span>{recipient.position + 1}. {recipient.displayNameSnapshot}</span><strong>{recipient.status}</strong></div>{recipient.resultNote && <p className="text-sm">Note : {recipient.resultNote}</p>}</li>)}</ul></section>}
    {(campaign.status === 'TERMINEE' || campaign.status === 'ANNULEE') && <section className="rounded-xl border bg-muted/50 p-4"><h2 className="font-semibold">Résumé immuable</h2><p>{progress.confirmed} confirmé(s), {progress.ignored} ignoré(s), {progress.errors} erreur(s), {progress.pending + progress.opened} restant(s).</p><p>Taux de confirmation manuelle : {progress.confirmationPercent} %. Aucune livraison, lecture ou réponse WhatsApp n’est mesurée.</p></section>}
  </main>;
}
