'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useEffect, useState } from 'react';
import { ManageCampaignsUseCase } from '../application/manage-campaigns';
import { CAMPAIGN_AUDIENCES, CampaignCriteria, CampaignDraftInput, CampaignPreview, segmentationSummary } from '../domain/campaign';
import type { CampaignFormOptions } from '../infrastructure/dexie-campaign-repository';

const manage = new ManageCampaignsUseCase();
const EMPTY_OPTIONS: CampaignFormOptions = { locations: [], products: [], tags: [], templates: [], prospectStatuses: [], interestLevels: [], sources: [] };

function MultiSelect({ label, values, options, onChange }: { label: string; values: string[]; options: Array<{ value: string; label: string }>; onChange: (values: string[]) => void }) {
  return <label className="grid gap-1 text-sm"><span>{label}</span><select multiple aria-label={label} className="min-h-28 rounded-md border p-2" value={values} onChange={(event) => onChange(Array.from(event.currentTarget.selectedOptions, (option) => option.value))}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><small className="text-slate-500">Ctrl/Cmd permet plusieurs choix.</small></label>;
}

export function CampaignEditor({ campaignId }: { campaignId?: string }) {
  const router = useRouter(); const [options, setOptions] = useState(EMPTY_OPTIONS); const [name, setName] = useState(''); const [objective, setObjective] = useState(''); const [audienceType, setAudienceType] = useState<CampaignDraftInput['audienceType']>('PROSPECTS'); const [criteria, setCriteria] = useState<CampaignCriteria>({}); const [templateId, setTemplateId] = useState(''); const [message, setMessage] = useState(''); const [preview, setPreview] = useState<CampaignPreview | null>(null); const [sample, setSample] = useState(0); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);

  useEffect(() => { void Promise.all([manage.formOptions(), campaignId ? manage.get(campaignId) : Promise.resolve(null)]).then(([formOptions, current]) => { setOptions(formOptions); if (current) { if (current.campaign.status !== 'BROUILLON' && current.campaign.status !== 'PRETE') throw new Error('Cette campagne est immuable'); setName(current.campaign.name); setObjective(current.campaign.objective ?? ''); setAudienceType(current.campaign.audienceType); setCriteria(current.campaign.criteria); setTemplateId(current.campaign.messageTemplateId ?? ''); setMessage(current.campaign.messageSnapshot); } }).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Chargement impossible')); }, [campaignId]);

  const input = (nextCriteria = criteria): CampaignDraftInput => ({ name, objective: objective || undefined, audienceType, criteria: nextCriteria, messageTemplateId: templateId || undefined, messageSnapshot: message });
  const runPreview = async (nextCriteria = criteria) => { setError(''); try { const value = await manage.preview(input(nextCriteria)); setPreview(value); setSample(0); return value; } catch (caught) { setError(caught instanceof Error ? caught.message : 'Prévisualisation impossible'); return null; } };
  const persist = async () => campaignId ? manage.update(campaignId, input()) : manage.create(input());
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const saved = await persist(); router.push(`/campaigns/${saved.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Enregistrement impossible'); } finally { setBusy(false); } };
  const saveReady = async () => { setBusy(true); setError(''); try { const currentPreview = await runPreview(); if (!currentPreview) return; const saved = await persist(); await manage.markReady(saved.id); router.push(`/campaigns/${saved.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Validation impossible'); } finally { setBusy(false); } };
  const setCriterion = <K extends keyof CampaignCriteria>(key: K, value: CampaignCriteria[K]) => { setCriteria((current) => ({ ...current, [key]: value })); setPreview(null); };
  const toggleManual = async (contactId: string, excluded: boolean) => { const current = new Set(criteria.excludedContactIds ?? []); if (excluded) current.add(contactId); else current.delete(contactId); const next = { ...criteria, excludedContactIds: [...current] }; setCriteria(next); await runPreview(next); };
  const allowEmpty = async (contactId: string) => { const next = { ...criteria, allowEmptyVariableContactIds: [...new Set([...(criteria.allowEmptyVariableContactIds ?? []), contactId])] }; setCriteria(next); await runPreview(next); };
  const samples = preview?.entries ?? []; const currentSample = samples[sample];

  return <main className="mx-auto max-w-6xl space-y-5 p-4 md:p-8"><Link href={campaignId ? `/campaigns/${campaignId}` : '/campaigns'} className="text-blue-700">← Campagnes</Link><header><h1 className="text-2xl font-bold">{campaignId ? 'Modifier la campagne' : 'Nouvelle campagne'}</h1><p className="text-slate-600">Sélection et préparation locales. Aucun message n’est envoyé automatiquement.</p></header>{error && <p role="alert" className="rounded-md bg-red-50 p-3 text-red-800">{error}</p>}
    <form className="space-y-5" onSubmit={save}>
      <section className="grid gap-4 rounded-xl border bg-white p-4 md:grid-cols-2"><label className="grid gap-1"><span>Nom *</span><input aria-label="Nom de la campagne" className="h-11 rounded-md border px-3" value={name} onChange={(event) => { setName(event.target.value); setPreview(null); }} /></label><label className="grid gap-1"><span>Audience</span><select aria-label="Audience de la campagne" className="h-11 rounded-md border px-3" value={audienceType} onChange={(event) => { setAudienceType(event.target.value as CampaignDraftInput['audienceType']); setPreview(null); }}>{CAMPAIGN_AUDIENCES.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="grid gap-1 md:col-span-2"><span>Objectif</span><input aria-label="Objectif de la campagne" className="h-11 rounded-md border px-3" value={objective} onChange={(event) => setObjective(event.target.value)} /></label></section>
      <section className="space-y-4 rounded-xl border bg-white p-4"><h2 className="font-semibold">Segmentation</h2><p className="text-sm text-slate-600">Familles combinées par ET; valeurs d’une famille par OU. Une région inclut ses descendants.</p><div className="grid gap-4 md:grid-cols-3"><MultiSelect label="Localités" values={criteria.locationIds ?? []} options={options.locations.map((item) => ({ value: item.id, label: `${item.name} (${item.level})` }))} onChange={(values) => setCriterion('locationIds', values)} /><MultiSelect label="Produits demandés" values={criteria.productInterestIds ?? []} options={options.products.map((item) => ({ value: item.id, label: item.name }))} onChange={(values) => setCriterion('productInterestIds', values)} /><MultiSelect label="Produits achetés" values={criteria.purchasedProductIds ?? []} options={options.products.map((item) => ({ value: item.id, label: item.name }))} onChange={(values) => setCriterion('purchasedProductIds', values)} /><MultiSelect label="Statuts prospects" values={criteria.prospectStatuses ?? []} options={options.prospectStatuses.map((item) => ({ value: item, label: item }))} onChange={(values) => setCriterion('prospectStatuses', values as NonNullable<CampaignCriteria['prospectStatuses']>)} /><MultiSelect label="Niveaux d’intérêt" values={criteria.interestLevels ?? []} options={options.interestLevels.map((item) => ({ value: item, label: item }))} onChange={(values) => setCriterion('interestLevels', values as NonNullable<CampaignCriteria['interestLevels']>)} /><MultiSelect label="Tags" values={criteria.tagIds ?? []} options={options.tags.map((item) => ({ value: item.id, label: item.name }))} onChange={(values) => setCriterion('tagIds', values)} /><MultiSelect label="Sources" values={criteria.sources ?? []} options={options.sources.map((item) => ({ value: item, label: item }))} onChange={(values) => setCriterion('sources', values as NonNullable<CampaignCriteria['sources']>)} /></div><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-sm"><span>Créés depuis</span><input aria-label="Contacts créés depuis" type="date" className="h-11 rounded-md border px-3" value={criteria.createdFrom ?? ''} onChange={(event) => setCriterion('createdFrom', event.target.value || undefined)} /></label><label className="grid gap-1 text-sm"><span>Créés jusqu’au</span><input aria-label="Contacts créés jusqu’au" type="date" className="h-11 rounded-md border px-3" value={criteria.createdTo ?? ''} onChange={(event) => setCriterion('createdTo', event.target.value || undefined)} /></label><label className="grid gap-1 text-sm"><span>Inactifs depuis</span><input aria-label="Inactifs depuis" type="date" className="h-11 rounded-md border px-3" value={criteria.inactiveSince ?? ''} onChange={(event) => setCriterion('inactiveSince', event.target.value || undefined)} /></label></div><p className="text-sm"><strong>Résumé :</strong> {segmentationSummary(criteria)}</p></section>
      <section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Message</h2><label className="grid gap-1"><span>Modèle actif</span><select aria-label="Modèle de campagne" className="h-11 rounded-md border px-3" value={templateId} onChange={(event) => { const id = event.target.value; setTemplateId(id); const template = options.templates.find((item) => item.id === id); if (template) setMessage(template.content); setPreview(null); }}><option value="">Message spécifique</option>{options.templates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1"><span>Contenu *</span><textarea aria-label="Message de campagne" className="min-h-36 rounded-md border p-3" value={message} onChange={(event) => { setMessage(event.target.value); setPreview(null); }} /></label><p className="text-xs text-slate-500">Variables : {'{{prenom}} {{nom}} {{contact}} {{entreprise}} {{produit}} {{localite}} {{nom_entreprise}}'}</p></section>
      <div className="flex flex-wrap gap-2"><button type="button" className="h-11 rounded-md border px-4" onClick={() => void runPreview()}>Prévisualiser l’audience</button><button disabled={busy} className="h-11 rounded-md bg-blue-700 px-4 text-white">Enregistrer le brouillon</button><button type="button" disabled={busy} className="h-11 rounded-md bg-emerald-700 px-4 text-white" onClick={() => void saveReady()}>Enregistrer et marquer prête</button></div>
    </form>
    {preview && <section className="space-y-4 rounded-xl border bg-white p-4" aria-label="Prévisualisation de campagne"><h2 className="font-semibold">Prévisualisation dynamique</h2><div className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-6"><span>Brut : <strong>{preview.rawCount}</strong></span><span>Admissibles : <strong>{preview.eligibleCount}</strong></span><span>Invalides : <strong>{preview.invalidPhoneCount}</strong></span><span>Archivés : <strong>{preview.archivedCount}</strong></span><span>Doublons : <strong>{preview.duplicateCount}</strong></span><span>Manuels : <strong>{preview.manualExclusionCount}</strong></span></div>{preview.unknownVariables.length > 0 && <p role="alert" className="text-red-700">Variables inconnues : {preview.unknownVariables.join(', ')}</p>}
      {currentSample && <article className="rounded-lg bg-slate-50 p-3"><div className="flex justify-between"><strong>Exemple personnalisé</strong><span>{sample + 1}/{samples.length}</span></div><p>{currentSample.displayName} · {currentSample.maskedPhone}</p><p className="mt-2 whitespace-pre-wrap">{currentSample.resolvedMessage}</p><div className="mt-2 flex gap-2"><button type="button" className="rounded border px-3 py-2" disabled={sample === 0} onClick={() => setSample((value) => value - 1)}>Précédent</button><button type="button" className="rounded border px-3 py-2" disabled={sample >= samples.length - 1} onClick={() => setSample((value) => value + 1)}>Suivant</button></div></article>}
      <div className="grid gap-3 md:grid-cols-2">{preview.entries.map((entry) => <article key={entry.contactId} className={`rounded-lg border p-3 ${entry.eligible ? 'border-emerald-300' : 'bg-slate-50'}`}><div className="flex justify-between gap-2"><strong>{entry.displayName}</strong><span>{entry.eligible ? 'ADMISSIBLE' : 'EXCLU'}</span></div><p className="text-sm">{entry.contactType} · {entry.maskedPhone} · {entry.locationName ?? 'Localité absente'}</p><p className="text-xs text-slate-600">Inclusion : {entry.inclusionReasons.join(', ')}</p>{entry.exclusionReasons.length > 0 && <p className="text-sm text-red-700">{entry.exclusionReasons.join(' · ')}</p>}<div className="mt-2 flex flex-wrap gap-2">{criteria.excludedContactIds?.includes(entry.contactId) ? <button type="button" className="rounded border px-3 py-2" onClick={() => void toggleManual(entry.contactId, false)}>Réinclure</button> : <button type="button" className="rounded border px-3 py-2" onClick={() => void toggleManual(entry.contactId, true)}>Exclure</button>}{entry.unresolvedVariables.length > 0 && !criteria.allowEmptyVariableContactIds?.includes(entry.contactId) && <button type="button" className="rounded border border-amber-600 px-3 py-2" onClick={() => void allowEmpty(entry.contactId)}>Confirmer les valeurs vides</button>}</div></article>)}</div>
    </section>}
  </main>;
}
