'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { ManageClientsUseCase } from '@/modules/clients/application/manage-clients';
import { ClientAggregate } from '@/modules/clients/domain/client';
import { buildWhatsAppUrl } from '@/modules/messages/domain/message-template';
import { ManageInvoicesUseCase } from '@/modules/invoices/application/manage-invoices';
import { formatMinor, InvoiceAggregate, sumSafeMinor } from '@/modules/invoices/domain/invoice';
import { ManagePaymentsUseCase } from '@/modules/payments/application/manage-payments';
import { PAYMENT_METHOD_LABELS, PaymentAggregate, ReceivableRecord, sumActivePayments } from '@/modules/payments/domain/payment';

const manage = new ManageClientsUseCase();
const manageInvoices = new ManageInvoicesUseCase();
const managePayments = new ManagePaymentsUseCase();
export default function ClientDetailPage() {
  const { id } = useParams<{ id: string }>(); const [client, setClient] = useState<ClientAggregate | null>(); const [invoices, setInvoices] = useState<InvoiceAggregate[]>([]); const [paymentItems, setPaymentItems] = useState<PaymentAggregate[]>([]); const [receivables, setReceivables] = useState<ReceivableRecord[]>([]); const [error, setError] = useState('');
  useEffect(() => { void manage.get(id).then(setClient).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Chargement impossible')); }, [id]);
  useEffect(() => { void manageInvoices.list({ clientProfileId: id }).then(setInvoices).catch(() => undefined); }, [id]);
  useEffect(() => { void Promise.all([managePayments.list({ clientProfileId: id }), managePayments.receivables({ clientProfileId: id })]).then(([values, debts]) => { setPaymentItems(values); setReceivables(debts); }).catch(() => undefined); }, [id]);
  if (error) return <p role="alert" className="p-4 text-red-700">{error}</p>; if (client === undefined) return <p className="p-4">Chargement...</p>; if (client === null) return <p className="p-4">Client introuvable.</p>;
  const whatsAppUrl = buildWhatsAppUrl(client.contact.normalizedWhatsappPhone, `Bonjour ${client.contact.displayName}`);
  const nextFollowUp = client.followUps.find((item) => item.status === 'PLANIFIEE');
  const activeInvoices = invoices.filter((item) => item.invoice.status === 'EMISE' || item.invoice.status === 'PARTIELLEMENT_PAYEE' || item.invoice.status === 'PAYEE'); const billed = sumSafeMinor(activeInvoices.map((item) => item.invoice.grandTotalMinor)); const balance = sumSafeMinor(activeInvoices.map((item) => item.invoice.balanceMinor)); const collected = sumActivePayments(paymentItems.map((item) => item.payment)); const invoiceCurrency = invoices[0]?.invoice.currency ?? paymentItems[0]?.payment.currency ?? 'XOF'; const invoiceScale = invoices[0]?.invoice.currencyScale ?? paymentItems[0]?.payment.currencyScale ?? 0;
  return <main className="mx-auto max-w-4xl space-y-5 p-4 md:p-8"><Link href="/clients" className="text-blue-700">← Clients</Link><header className="rounded-xl border bg-card text-card-foreground p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{client.contact.displayName}</h1><p>Client depuis le {new Date(client.profile.convertedAt).toLocaleString('fr-FR')}</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-800">CLIENT</span></div><div className="mt-4 flex flex-wrap gap-2"><a href={whatsAppUrl} target="_blank" rel="noopener noreferrer" className="rounded-md bg-green-700 px-4 py-3 text-white">WhatsApp</a><Link href={`/follow-ups/new?contactId=${client.contact.id}`} className="rounded-md border px-4 py-3">Relancer</Link><Link href={`/invoices/new?clientId=${client.profile.id}`} className="rounded-md bg-blue-700 px-4 py-3 text-white">Créer une facture</Link></div></header>
    <section className="grid gap-3 sm:grid-cols-4"><div className="rounded-xl border bg-card text-card-foreground p-4"><p className="text-xs text-slate-500">Total facturé</p><strong>{formatMinor(billed, invoiceCurrency, invoiceScale)}</strong></div><div className="rounded-xl border bg-card text-card-foreground p-4"><p className="text-xs text-slate-500">Total encaissé</p><strong>{formatMinor(collected, invoiceCurrency, invoiceScale)}</strong></div><div className="rounded-xl border bg-card text-card-foreground p-4"><p className="text-xs text-slate-500">Solde dû</p><strong>{formatMinor(balance, invoiceCurrency, invoiceScale)}</strong></div><div className="rounded-xl border bg-card text-card-foreground p-4"><p className="text-xs text-slate-500">Créances échues</p><strong>{receivables.filter((item) => item.daysOverdue > 0).length}</strong></div></section>
    <section className="rounded-xl border bg-card text-card-foreground p-5"><h2 className="font-semibold">Coordonnées et intérêts conservés</h2><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Téléphone</dt><dd>{client.contact.whatsappPhone}</dd></div><div><dt className="text-slate-500">Localité</dt><dd>{client.locationName || 'Non renseignée'}</dd></div><div><dt className="text-slate-500">Entreprise</dt><dd>{client.contact.companyName || 'Non renseignée'}</dd></div><div><dt className="text-slate-500">Produits demandés</dt><dd>{client.productNames.join(', ') || 'Aucun'}</dd></div><div><dt className="text-slate-500">Tags</dt><dd>{client.tags.map((tag) => tag.name).join(', ') || 'Aucun'}</dd></div></dl></section>
    <section className="rounded-xl border bg-card text-card-foreground p-5"><h2 className="font-semibold">Relances conservées</h2><p className="mt-2 text-sm"><span className="text-slate-500">Prochaine relance : </span>{nextFollowUp ? <Link className="text-blue-700 underline" href={`/follow-ups/${nextFollowUp.id}`}>{new Date(nextFollowUp.dueAt).toLocaleString('fr-FR')} — {nextFollowUp.reason || nextFollowUp.channel}</Link> : 'Aucune relance future'}</p>{client.followUps.length > 0 ? <ul className="mt-3 space-y-2 text-sm">{client.followUps.map((item) => <li key={item.id} className="rounded-md border p-3"><Link href={`/follow-ups/${item.id}`} className="font-medium text-blue-700">{new Date(item.dueAt).toLocaleString('fr-FR')} — {item.status}</Link>{item.reason && <p>{item.reason}</p>}{item.resultNote && <p className="text-slate-600">Résultat : {item.resultNote}</p>}</li>)}</ul> : <p className="mt-3 text-sm">Aucune relance.</p>}</section>
    <section className="rounded-xl border bg-card text-card-foreground p-5"><h2 className="font-semibold">Notes commerciales</h2>{client.notes.length > 0 ? <ul className="mt-3 space-y-2">{client.notes.map((note) => <li key={note.id} className="whitespace-pre-wrap rounded-md bg-slate-50 p-3 text-sm">{note.content}</li>)}</ul> : <p className="mt-3 text-sm">Aucune note.</p>}</section>
    <section className="rounded-xl border bg-card text-card-foreground p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">Factures</h2><Link href={`/invoices/new?clientId=${client.profile.id}`} className="text-blue-700">Nouvelle facture</Link></div>{invoices.length === 0 ? <p className="mt-3 text-sm">Aucune facture.</p> : <ul className="mt-3 space-y-2">{invoices.map((item) => <li key={item.invoice.id}><Link href={`/invoices/${item.invoice.id}`} className="flex justify-between rounded-md border p-3"><span>{item.invoice.number || 'Brouillon'}</span><span>{item.invoice.status} · {formatMinor(item.invoice.grandTotalMinor, item.invoice.currency, item.invoice.currencyScale)}</span></Link></li>)}</ul>}</section>
    <section className="rounded-xl border bg-card text-card-foreground p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">Paiements</h2><Link href="/payments" className="text-blue-700">Tous les paiements</Link></div>{paymentItems.length === 0 ? <p className="mt-3 text-sm">Aucun paiement.</p> : <ul className="mt-3 space-y-2">{paymentItems.map(({ payment, invoiceNumber }) => <li key={payment.id} className={`rounded-md border p-3 ${payment.status === 'REVERSED' ? 'bg-slate-100 text-slate-600' : ''}`}><div className="flex flex-wrap justify-between gap-2"><Link href={`/invoices/${payment.invoiceId}`} className="font-medium text-blue-700">{invoiceNumber}</Link><span>{payment.status}</span></div><p>{formatMinor(payment.amountMinor, payment.currency, payment.currencyScale)} · {PAYMENT_METHOD_LABELS[payment.method]} · {payment.paymentDate}</p>{payment.reversalReason && <p className="text-sm">Motif : {payment.reversalReason}</p>}</li>)}</ul>}</section>
    <section className="rounded-xl border bg-card text-card-foreground p-5"><h2 className="font-semibold">Chronologie commerciale</h2>{client.events.length === 0 ? <p className="mt-3 text-sm">Aucun événement.</p> : <ol className="mt-3 space-y-3">{client.events.map((event) => <li key={event.id} className="border-l-2 border-slate-200 pl-4"><div className="flex flex-wrap justify-between gap-2"><strong>{event.title}</strong><time className="text-xs">{new Date(event.occurredAt).toLocaleString('fr-FR')}</time></div>{event.summary && <p className="text-sm text-slate-600">{event.summary}</p>}<span className="text-xs text-slate-500">{event.type}</span></li>)}</ol>}</section>
  </main>;
}
