import Dexie from 'dexie';
import { afterEach, describe, expect, it } from 'vitest';
import { SamtechCRMDatabase } from './db';

const V8_STORES = {
  contacts: 'id, normalizedWhatsappPhone, displayName, locationId, source, createdAt, updatedAt, archivedAt', prospectProfiles: 'id, &contactId, status, interestLevel, firstContactDate, convertedAt, lastStatusChangedAt, archivedAt, [status+interestLevel]', settings: '&key, updatedAt', sequences: '&key, updatedAt', locations: 'id, name, normalizedName, level, parentId, archivedAt, [parentId+level], [parentId+normalizedName]', categories: 'id, name, normalizedName, archivedAt', products: 'id, name, normalizedName, type, categoryId, sku, isActive, archivedAt, [categoryId+isActive]', prospectInterests: 'id, prospectProfileId, productId, interestLevel, requestedAt, archivedAt, [prospectProfileId+productId], [productId+requestedAt]', followUps: 'id, contactId, channel, dueAt, priority, status, completedAt, previousFollowUpId, archivedAt, [status+dueAt], [contactId+status]', messageTemplates: 'id, name, category, isActive, archivedAt, [category+isActive]', timelineEvents: 'id, contactId, type, occurredAt, sourceEntityId, [contactId+occurredAt], [sourceEntityType+sourceEntityId]', clientProfiles: 'id, &contactId, convertedAt, clientNumber, lastPurchaseAt, archivedAt', tags: 'id, &normalizedName, name, archivedAt', contactTags: 'id, contactId, tagId, &[contactId+tagId]', notes: 'id, contactId, pinned, createdAt, updatedAt, archivedAt, [contactId+createdAt]', invoices: 'id, &number, clientProfileId, status, issueDate, dueDate, issuedAt, archivedAt, [clientProfileId+issueDate], [status+dueDate]', invoiceLines: 'id, invoiceId, productId, position, [invoiceId+position], [productId+createdAt]', payments: 'id, invoiceId, clientProfileId, paymentDate, method, status, createdAt, [invoiceId+status], [clientProfileId+paymentDate]',
};

describe('Migration Dexie V8 vers V9', () => {
  const name = 'samtech-v8-v9-migration'; afterEach(async () => Dexie.delete(name));
  it('préserve chaque table V8 et persiste campagnes et destinataires après réouverture', async () => {
    const now = '2026-07-18T10:00:00.000Z'; const v8 = new Dexie(name); v8.version(8).stores(V8_STORES); await v8.open();
    const fixtures: Record<string, Record<string, unknown>> = {
      contacts: { id: 'contact1', displayName: 'Client migration', whatsappPhone: '+221770000001', normalizedWhatsappPhone: '+221770000001', locationId: 'location1', source: 'REFERRAL', createdAt: now, updatedAt: now },
      prospectProfiles: { id: 'prospect1', contactId: 'contact1', status: 'CONVERTI', interestLevel: 'CHAUD', firstContactDate: '2026-01-01', lastStatusChangedAt: now, convertedAt: now, createdAt: now, updatedAt: now },
      settings: { key: 'company.profile', value: { name: 'SAMTECH' }, schemaVersion: 1, updatedAt: now }, sequences: { key: 'invoice:2026', prefix: 'FAC-', period: '2026', nextValue: 2, padding: 4, updatedAt: now },
      locations: { id: 'location1', name: 'Dakar', normalizedName: 'dakar', level: 'CITY', createdAt: now, updatedAt: now }, categories: { id: 'category1', name: 'Services', normalizedName: 'services', createdAt: now, updatedAt: now },
      products: { id: 'product1', name: 'Conseil', normalizedName: 'conseil', type: 'SERVICE', unitPriceMinor: 100000, currency: 'XOF', currencyScale: 0, isActive: true, createdAt: now, updatedAt: now }, prospectInterests: { id: 'interest1', prospectProfileId: 'prospect1', productId: 'product1', requestedAt: now, createdAt: now, updatedAt: now },
      followUps: { id: 'follow1', contactId: 'contact1', channel: 'WHATSAPP', dueAt: now, timezone: 'Africa/Dakar', priority: 'NORMAL', status: 'REALISEE', createdAt: now, updatedAt: now }, messageTemplates: { id: 'template1', name: 'Campagne', category: 'PROMOTION', content: 'Bonjour {{prenom}}', variables: ['prenom'], isActive: true, createdAt: now, updatedAt: now },
      timelineEvents: { id: 'event1', contactId: 'contact1', type: 'PAYMENT_RECORDED', occurredAt: now, createdAt: now, title: 'Paiement', payloadVersion: 1 }, clientProfiles: { id: 'client1', contactId: 'contact1', convertedAt: now, createdAt: now, updatedAt: now }, tags: { id: 'tag1', name: 'VIP', normalizedName: 'vip', createdAt: now, updatedAt: now }, contactTags: { id: 'contactTag1', contactId: 'contact1', tagId: 'tag1', createdAt: now }, notes: { id: 'note1', contactId: 'contact1', content: 'Note', pinned: false, createdAt: now, updatedAt: now },
      invoices: { id: 'invoice1', clientProfileId: 'client1', number: 'FAC-2026-0001', status: 'PARTIELLEMENT_PAYEE', issueDate: '2026-07-17', currency: 'XOF', currencyScale: 0, companySnapshot: { displayName: 'SAMTECH' }, clientSnapshot: { displayName: 'Client migration' }, subtotalMinor: 100000, discountTotalMinor: 0, taxTotalMinor: 0, grandTotalMinor: 100000, paidTotalMinor: 30000, balanceMinor: 70000, createdAt: now, updatedAt: now }, invoiceLines: { id: 'line1', invoiceId: 'invoice1', productId: 'product1', position: 0, designationSnapshot: 'Conseil', quantityScaled: 1, quantityScale: 0, unitPriceMinor: 100000, grossMinor: 100000, discountType: 'NONE', discountValue: 0, discountMinor: 0, taxRateBasisPoints: 0, taxMinor: 0, lineTotalMinor: 100000, createdAt: now, updatedAt: now }, payments: { id: 'payment1', invoiceId: 'invoice1', clientProfileId: 'client1', paymentDate: '2026-07-18', amountMinor: 30000, currency: 'XOF', currencyScale: 0, method: 'WAVE', status: 'ACTIVE', createdAt: now, updatedAt: now },
    };
    for (const [table, record] of Object.entries(fixtures)) await v8.table(table).add(record); v8.close();
    const v9 = new SamtechCRMDatabase(name); await v9.open(); expect(v9.verno).toBe(10); for (const table of Object.keys(fixtures)) expect(await v9.table(table).count(), table).toBe(1);
    await v9.campaigns.add({ id: 'campaign1', name: 'Migration', status: 'EN_COURS', audienceType: 'CLIENTS', criteria: {}, messageSnapshot: 'Bonjour', launchedAt: now, createdAt: now, updatedAt: now });
    await v9.campaignRecipients.bulkAdd([{ id: 'recipient1', campaignId: 'campaign1', contactId: 'contact1', normalizedPhoneSnapshot: '+221770000001', displayNameSnapshot: 'Client migration', resolvedMessageSnapshot: 'Bonjour', position: 0, status: 'A_TRAITER', createdAt: now, updatedAt: now }, { id: 'recipient2', campaignId: 'campaign1', contactId: 'contact2', normalizedPhoneSnapshot: '+221770000002', displayNameSnapshot: 'Deuxième', resolvedMessageSnapshot: 'Bonjour', position: 1, status: 'IGNORE', resultNote: 'Test', createdAt: now, updatedAt: now }]); v9.close();
    const reopened = new SamtechCRMDatabase(name); await reopened.open(); for (const table of Object.keys(fixtures)) expect(await reopened.table(table).count(), `V8 ${table}`).toBe(1); expect(await reopened.campaigns.get('campaign1')).toMatchObject({ status: 'EN_COURS', messageSnapshot: 'Bonjour' }); expect(await reopened.campaignRecipients.where('[campaignId+position]').between(['campaign1', 0], ['campaign1', 99]).count()).toBe(2); reopened.close();
  });
});
