import Dexie from 'dexie';
import { afterEach, describe, expect, it } from 'vitest';
import { SamtechCRMDatabase } from './db';

describe('Migration Dexie V6 vers V7', () => {
  const name = 'samtech-v6-v7-migration'; afterEach(async () => Dexie.delete(name));
  it('préserve chaque table V6, ajoute factures et lignes puis survit à la réouverture', async () => {
    const now = '2026-07-17T12:00:00.000Z'; const v6 = new Dexie(name);
    v6.version(6).stores({ contacts: 'id, normalizedWhatsappPhone, displayName, locationId, source, createdAt, updatedAt, archivedAt', prospectProfiles: 'id, &contactId, status, interestLevel, firstContactDate, convertedAt, lastStatusChangedAt, archivedAt, [status+interestLevel]', settings: '&key, updatedAt', sequences: '&key, period, updatedAt', locations: 'id, name, normalizedName, level, parentId, archivedAt, [parentId+level], [parentId+normalizedName]', categories: 'id, name, normalizedName, archivedAt', products: 'id, name, normalizedName, type, categoryId, sku, isActive, archivedAt, [categoryId+isActive]', prospectInterests: 'id, prospectProfileId, productId, interestLevel, requestedAt, archivedAt, [prospectProfileId+productId], [productId+requestedAt]', followUps: 'id, contactId, channel, dueAt, priority, status, completedAt, previousFollowUpId, archivedAt, [status+dueAt], [contactId+status]', messageTemplates: 'id, name, category, isActive, archivedAt, [category+isActive]', timelineEvents: 'id, contactId, type, occurredAt, sourceEntityId, [contactId+occurredAt], [sourceEntityType+sourceEntityId]', clientProfiles: 'id, &contactId, convertedAt, clientNumber, lastPurchaseAt, archivedAt', tags: 'id, &normalizedName, name, archivedAt', contactTags: 'id, contactId, tagId, &[contactId+tagId]', notes: 'id, contactId, pinned, createdAt, updatedAt, archivedAt, [contactId+createdAt]' });
    await v6.open(); const fixtures: Record<string, Record<string, unknown>> = { contacts: { id: 'c1', displayName: 'Awa', companyName: 'Démonstration', whatsappPhone: '+221770000000', normalizedWhatsappPhone: '+221770000000', locationId: 'l1', source: 'REFERENCE', createdAt: now, updatedAt: now }, prospectProfiles: { id: 'p1', contactId: 'c1', status: 'CONVERTI', interestLevel: 'CHAUD', firstContactDate: '2026-07-01', convertedAt: now, lastStatusChangedAt: now, createdAt: now, updatedAt: now }, settings: { key: 'company.profile', value: { name: 'SAMTECH', phone: '+221330000000', currencyCode: 'XOF', currencySymbol: 'FCFA' }, schemaVersion: 1, updatedAt: now }, sequences: { key: 'invoice:2026', prefix: 'FAC-', period: '2026', nextValue: 1, padding: 4, updatedAt: now }, locations: { id: 'l1', name: 'Dakar', normalizedName: 'dakar', level: 'CITY', createdAt: now, updatedAt: now }, categories: { id: 'cat1', name: 'Services', normalizedName: 'services', createdAt: now, updatedAt: now }, products: { id: 'prod1', name: 'Audit', normalizedName: 'audit', type: 'SERVICE', categoryId: 'cat1', unitPriceMinor: 1000, currency: 'XOF', currencyScale: 0, isActive: true, createdAt: now, updatedAt: now }, prospectInterests: { id: 'i1', prospectProfileId: 'p1', productId: 'prod1', requestedAt: now, createdAt: now, updatedAt: now }, followUps: { id: 'f1', contactId: 'c1', channel: 'PHONE', dueAt: now, timezone: 'Africa/Dakar', priority: 'NORMAL', status: 'PLANIFIEE', reason: 'Relance de migration', createdAt: now, updatedAt: now }, messageTemplates: { id: 'm1', name: 'Relance', category: 'FOLLOW_UP', content: 'Bonjour {{contact}}', isActive: true, createdAt: now, updatedAt: now }, timelineEvents: { id: 'e1', contactId: 'c1', type: 'PROSPECT_CONVERTED', occurredAt: now, createdAt: now, sourceEntityType: 'PROSPECT', sourceEntityId: 'p1', title: 'Prospect converti', payloadVersion: 1 }, clientProfiles: { id: 'client1', contactId: 'c1', convertedAt: now, createdAt: now, updatedAt: now }, tags: { id: 'tag1', name: 'VIP', normalizedName: 'vip', createdAt: now, updatedAt: now }, contactTags: { id: 'ct1', contactId: 'c1', tagId: 'tag1', createdAt: now }, notes: { id: 'n1', contactId: 'c1', content: 'Historique', pinned: true, createdAt: now, updatedAt: now } };
    for (const [table, value] of Object.entries(fixtures)) await v6.table(table).add(value); v6.close();
    const v7 = new SamtechCRMDatabase(name); await v7.open(); expect(v7.verno).toBe(13); for (const table of Object.keys(fixtures)) expect(await v7.table(table).count(), table).toBe(1);
    await v7.transaction('rw', v7.invoices, v7.invoiceLines, async () => { await v7.invoices.add({ id: 'inv1', clientProfileId: 'client1', status: 'BROUILLON', currency: 'XOF', currencyScale: 0, companySnapshot: { displayName: '' }, clientSnapshot: { displayName: '' }, subtotalMinor: 1000, discountTotalMinor: 0, taxTotalMinor: 0, grandTotalMinor: 1000, paidTotalMinor: 0, balanceMinor: 1000, createdAt: now, updatedAt: now }); await v7.invoiceLines.add({ id: 'line1', invoiceId: 'inv1', productId: 'prod1', position: 0, designationSnapshot: 'Audit', quantityScaled: 1, quantityScale: 0, unitPriceMinor: 1000, grossMinor: 1000, discountType: 'NONE', discountValue: 0, discountMinor: 0, taxRateBasisPoints: 0, taxMinor: 0, lineTotalMinor: 1000, createdAt: now, updatedAt: now }); }); v7.close();
    const reopened = new SamtechCRMDatabase(name); await reopened.open(); for (const table of Object.keys(fixtures)) expect(await reopened.table(table).count(), table).toBe(1); expect(await reopened.invoices.get('inv1')).toMatchObject({ clientProfileId: 'client1', grandTotalMinor: 1000 }); expect(await reopened.invoiceLines.get('line1')).toMatchObject({ invoiceId: 'inv1', productId: 'prod1' }); reopened.close();
  });
});
