'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Archive, Save } from 'lucide-react';
import { TAG_COLORS, TAG_ICONS, TagIcon as TagIconName, TagRecord } from '@/modules/prospects/domain/prospect';
import { ManageTagsUseCase } from '../application/manage-tags';
import { TagIcon } from './TagIcon';

const tagsUseCase = new ManageTagsUseCase();
const empty = { name: '', color: '#0B6B2D' as (typeof TAG_COLORS)[number], icon: 'TAG' as TagIconName };

export default function TagsManager() {
  const [tags, setTags] = useState<TagRecord[]>([]); const [draft, setDraft] = useState(empty); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = () => tagsUseCase.listActive().then(setTags).catch((caught) => setError(caught instanceof Error ? caught.message : 'Chargement des tags impossible'));
  useEffect(() => { void load(); }, []);
  const create = async (event: FormEvent) => { event.preventDefault(); setError(''); setSaving(true); try { await tagsUseCase.create(draft); setDraft(empty); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Création impossible'); } finally { setSaving(false); } };
  const update = async (tag: TagRecord) => { setError(''); setSaving(true); try { await tagsUseCase.update(tag.id, { name: tag.name, color: (tag.color || '#0B6B2D') as (typeof TAG_COLORS)[number], icon: tag.icon || 'TAG' }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Mise à jour impossible'); } finally { setSaving(false); } };
  const archive = async (id: string) => { if (!confirm('Retirer ce tag de tous les contacts ?')) return; setError(''); try { await tagsUseCase.archive(id); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Suppression impossible'); } };
  const replace = (id: string, changes: Partial<TagRecord>) => setTags((items) => items.map((tag) => tag.id === id ? { ...tag, ...changes } : tag));
  return <section className="space-y-5"><header><h2 className="text-lg font-semibold">Tags clients et prospects</h2><p className="text-sm text-muted-foreground">Créez des repères visuels réutilisables dans les fiches contacts.</p></header>{error && <p role="alert" className="rounded-md bg-red-500/10 p-3 text-sm text-red-800 dark:text-red-200">{error}</p>}<form onSubmit={create} className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-[1fr_auto_auto_auto]"><input required maxLength={40} aria-label="Nom du tag" className="h-11 rounded-md border bg-background px-3" placeholder="Ex. Client VIP" value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })}/><select aria-label="Icône du tag" className="h-11 rounded-md border bg-background px-3" value={draft.icon} onChange={(e) => setDraft({ ...draft, icon: e.target.value as TagIconName })}>{TAG_ICONS.map((icon) => <option key={icon}>{icon}</option>)}</select><select aria-label="Couleur du tag" className="h-11 rounded-md border bg-background px-3" value={draft.color} onChange={(e) => setDraft({ ...draft, color: e.target.value as (typeof TAG_COLORS)[number] })}>{TAG_COLORS.map((color) => <option key={color} value={color}>{color}</option>)}</select><button disabled={saving} className="h-11 rounded-md bg-emerald-700 px-4 text-white">Ajouter</button></form><div className="space-y-3">{tags.map((tag) => <div key={tag.id} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[auto_1fr_auto_auto_auto]"><span className="flex size-11 items-center justify-center rounded-full" style={{ color: tag.color || '#0B6B2D', backgroundColor: `${tag.color || '#0B6B2D'}20` }}><TagIcon icon={tag.icon} className="size-5" /></span><input aria-label={`Nom ${tag.name}`} className="h-11 rounded-md border bg-background px-3" value={tag.name} onChange={(e) => replace(tag.id, { name: e.target.value })}/><select aria-label={`Icône ${tag.name}`} className="h-11 rounded-md border bg-background px-3" value={tag.icon || 'TAG'} onChange={(e) => replace(tag.id, { icon: e.target.value as TagIconName })}>{TAG_ICONS.map((icon) => <option key={icon}>{icon}</option>)}</select><select aria-label={`Couleur ${tag.name}`} className="h-11 rounded-md border bg-background px-3" value={tag.color || '#0B6B2D'} onChange={(e) => replace(tag.id, { color: e.target.value })}>{TAG_COLORS.map((color) => <option key={color} value={color}>{color}</option>)}</select><div className="flex gap-2"><button type="button" aria-label={`Enregistrer ${tag.name}`} onClick={() => void update(tag)} className="inline-flex size-11 items-center justify-center rounded-md border"><Save className="size-4" /></button><button type="button" aria-label={`Archiver ${tag.name}`} onClick={() => void archive(tag.id)} className="inline-flex size-11 items-center justify-center rounded-md border text-red-700"><Archive className="size-4" /></button></div></div>)}{!tags.length && <p className="text-sm text-muted-foreground">Aucun tag configuré.</p>}</div></section>;
}
