import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from 'pdf-lib';
import { formatMinor, formatQuantity, InvoiceAggregate } from '../domain/invoice';

const A4: [number, number] = [595.28, 841.89]; const MARGIN = 44; const BOTTOM = 48;
export const PDF_MIME_TYPE = 'application/pdf';
export function safePdfFilename(number?: string, status?: string) { const base = number || (status === 'BROUILLON' ? 'brouillon' : 'facture'); return `facture-${base.toLocaleLowerCase('fr').replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'document'}.pdf`; }
export function invoiceFinancialSummary(value: InvoiceAggregate): string[] { return [`TOTAL : ${formatMinor(value.invoice.grandTotalMinor, value.invoice.currency, value.invoice.currencyScale)}`, `Payé : ${formatMinor(value.invoice.paidTotalMinor, value.invoice.currency, value.invoice.currencyScale)}`, `Solde : ${formatMinor(value.invoice.balanceMinor, value.invoice.currency, value.invoice.currencyScale)}`]; }
function safeText(value: unknown): string { return String(value ?? '').replace(/[\u00A0\u202F]/g, ' ').replace(/[‐‑‒–—―]/g, '-').replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/[^\x20-\x7E\xA0-\xFF\u0152\u0153\u20AC\n]/g, '?'); }
function wrap(text: string, font: PDFFont, size: number, width: number): string[] { const paragraphs = safeText(text).split('\n'); const result: string[] = []; for (const paragraph of paragraphs) { const words = paragraph.split(/\s+/).filter(Boolean); if (!words.length) { result.push(''); continue; } let line = ''; for (const word of words) { const candidate = line ? `${line} ${word}` : word; if (font.widthOfTextAtSize(candidate, size) <= width) line = candidate; else { if (line) result.push(line); let chunk = ''; for (const char of word) { const next = chunk + char; if (font.widthOfTextAtSize(next, size) > width && chunk) { result.push(chunk); chunk = char; } else chunk = next; } line = chunk; } } if (line) result.push(line); } return result; }

export async function generateInvoicePdf(value: InvoiceAggregate): Promise<Uint8Array> {
  const document = await PDFDocument.create(); const regular = await document.embedFont(StandardFonts.Helvetica); const bold = await document.embedFont(StandardFonts.HelveticaBold); document.setTitle(safeText(value.invoice.number || 'Facture brouillon')); document.setSubject(safeText(`SAMTECH CRM - ${value.invoice.status} - ${value.invoice.companySnapshot.displayName} - ${value.invoice.clientSnapshot.displayName || value.clientName} - ${value.invoice.currency}`)); document.setCreator('SAMTECH CRM'); document.setCreationDate(new Date(value.invoice.issuedAt || value.invoice.createdAt));
  let page!: PDFPage; let y = 0; const pages: PDFPage[] = [];
  const addPage = () => { page = document.addPage(A4); pages.push(page); y = A4[1] - MARGIN; page.drawText(safeText(value.invoice.companySnapshot.displayName || 'Entreprise'), { x: MARGIN, y, size: 16, font: bold, color: rgb(0.08, 0.16, 0.28) }); page.drawText(safeText(value.invoice.status === 'BROUILLON' ? 'FACTURE - BROUILLON' : `FACTURE ${value.invoice.number || ''}`), { x: 330, y, size: 12, font: bold }); y -= 24; page.drawLine({ start: { x: MARGIN, y }, end: { x: A4[0] - MARGIN, y }, thickness: 1, color: rgb(0.75, 0.78, 0.82) }); y -= 18; };
  const ensure = (height: number) => { if (y - height < BOTTOM) addPage(); };
  const text = (content: string, options: { size?: number; font?: PDFFont; x?: number; width?: number; gap?: number; color?: ReturnType<typeof rgb> } = {}) => { const size = options.size ?? 10; const font = options.font ?? regular; const x = options.x ?? MARGIN; const width = options.width ?? A4[0] - MARGIN * 2; const lines = wrap(content, font, size, width); ensure(lines.length * (size + 3) + (options.gap ?? 0)); for (const line of lines) { page.drawText(line, { x, y, size, font, color: options.color }); y -= size + 3; } y -= options.gap ?? 0; };
  addPage();
  if (value.invoice.status === 'ANNULEE') { text('ANNULÉE', { size: 24, font: bold, color: rgb(0.75, 0.05, 0.05), gap: 8 }); }
  text(`Statut : ${value.invoice.status}`, { font: bold }); text(`Date d'émission : ${value.invoice.issueDate || 'Non émise'}`); text(`Échéance : ${value.invoice.dueDate || 'Non renseignée'}`, { gap: 10 });
  text('ENTREPRISE', { font: bold, size: 11 }); text([value.invoice.companySnapshot.displayName, value.invoice.companySnapshot.address, value.invoice.companySnapshot.phone, value.invoice.companySnapshot.email].filter(Boolean).join(' - '), { gap: 8 });
  text('CLIENT', { font: bold, size: 11 }); text([value.invoice.clientSnapshot.displayName || value.clientName, value.invoice.clientSnapshot.address, value.invoice.clientSnapshot.phone, value.invoice.clientSnapshot.email].filter(Boolean).join(' - '), { gap: 12 });
  text('LIGNES', { font: bold, size: 11, gap: 3 });
  for (const line of value.lines) { ensure(72); text(`${line.position + 1}. ${line.designationSnapshot}`, { font: bold, size: 10 }); if (line.descriptionSnapshot) text(line.descriptionSnapshot, { size: 9 }); text(`Quantité : ${formatQuantity(line.quantityScaled, line.quantityScale)} ${line.unitLabelSnapshot || ''} | Prix : ${formatMinor(line.unitPriceMinor, value.invoice.currency, value.invoice.currencyScale)} | Total : ${formatMinor(line.lineTotalMinor, value.invoice.currency, value.invoice.currencyScale)}`, { size: 9 }); if (line.discountMinor || line.taxMinor) text(`Remise : ${formatMinor(line.discountMinor, value.invoice.currency, value.invoice.currencyScale)} | Taxe : ${formatMinor(line.taxMinor, value.invoice.currency, value.invoice.currencyScale)}`, { size: 8 }); page.drawLine({ start: { x: MARGIN, y }, end: { x: A4[0] - MARGIN, y }, thickness: 0.5, color: rgb(0.85, 0.87, 0.9) }); y -= 8; }
  ensure(120); text(`Sous-total : ${formatMinor(value.invoice.subtotalMinor, value.invoice.currency, value.invoice.currencyScale)}`, { x: 300, width: 250 }); text(`Remises : ${formatMinor(value.invoice.discountTotalMinor, value.invoice.currency, value.invoice.currencyScale)}`, { x: 300, width: 250 }); text(`Taxes : ${formatMinor(value.invoice.taxTotalMinor, value.invoice.currency, value.invoice.currencyScale)}`, { x: 300, width: 250 }); const [totalLabel, paidLabel, balanceLabel] = invoiceFinancialSummary(value); text(totalLabel, { x: 300, width: 250, size: 13, font: bold }); text(paidLabel, { x: 300, width: 250 }); text(balanceLabel, { x: 300, width: 250, font: bold, gap: 10 });
  const section = (title: string, content: string, gap = 0) => { const firstBodyLines = Math.min(wrap(content, regular, 10, A4[0] - MARGIN * 2).length, 2); ensure(14 + firstBodyLines * 13 + gap); text(title, { font: bold }); text(content, { gap }); };
  if (value.invoice.notes) section('NOTES', value.invoice.notes, 8); if (value.invoice.terms) section('CONDITIONS', value.invoice.terms); if (value.invoice.status === 'ANNULEE') { text(`Motif d'annulation : ${value.invoice.cancellationReason || ''}`, { font: bold, color: rgb(0.65, 0.05, 0.05) }); }
  pages.forEach((item, index) => item.drawText(`Page ${index + 1} / ${pages.length}`, { x: A4[0] / 2 - 20, y: 22, size: 8, font: regular, color: rgb(0.4, 0.43, 0.48) }));
  return document.save({ useObjectStreams: false });
}

export function downloadPdf(bytes: Uint8Array, filename: string) { const blob = new Blob([Uint8Array.from(bytes)], { type: PDF_MIME_TYPE }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
export async function shareOrDownloadPdf(bytes: Uint8Array, filename: string): Promise<'SHARED' | 'DOWNLOADED'> { const blob = new Blob([Uint8Array.from(bytes)], { type: PDF_MIME_TYPE }); const file = new File([blob], filename, { type: PDF_MIME_TYPE }); if (navigator.share && navigator.canShare?.({ files: [file] })) { await navigator.share({ files: [file], title: filename }); return 'SHARED'; } downloadPdf(bytes, filename); return 'DOWNLOADED'; }
